# Generated by Django 5.2.17 on 2026-09-24 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='考试时长（分钟）')),
                ('passing_score', models.FloatField(default=60, verbose_name='及格分数')),
                ('total_score', models.FloatField(default=100, verbose_name='满分')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='课程')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='出题人')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True, verbose_name='最终得分')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='是否及格')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multi', '多选题'), ('judge', '判断题')], max_length=16, verbose_name='题型')),
                ('title', models.TextField(verbose_name='题干')),
                ('options', models.JSONField(default=dict, verbose_name='选项（JSON：{"A":"...","B":"..."}）')),
                ('correct_answer', models.JSONField(verbose_name='正确答案（JSON：单选存"A"；多选存["A","C"]；判断存true/false）')),
                ('analysis', models.TextField(blank=True, default='', verbose_name='解析')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, verbose_name='难度 1-5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='课程')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('kp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.knowledgepoint', verbose_name='知识点')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.JSONField(blank=True, null=True, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score_obtained', models.FloatField(default=0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examrecord')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=5, verbose_name='本题分值')),
                ('order_no', models.IntegerField(default=0, verbose_name='排序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_items', to='exams.question')),
            ],
            options={
                'ordering': ['order_no', 'id'],
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
