# Generated by Django 5.2.15 on 2026-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='page_type',
            field=models.CharField(choices=[('about', '学校简介'), ('school_history', '历史沿革'), ('campus_culture', '校园文化'), ('education_philosophy', '办学理念'), ('school_vision', '学校愿景')], default='about', max_length=20, verbose_name='页面类型'),
        ),
    ]
