# Generated by Django 5.2.15 on 2026-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='可直接填写或留空仅上传文件', verbose_name='内容')),
                ('pdf_file', models.FileField(blank=True, upload_to='admissions/brochures/', verbose_name='PDF文件')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前有效')),
            ],
            options={
                'verbose_name': '招生简章',
                'verbose_name_plural': '招生简章',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('description', models.TextField(verbose_name='岗位描述')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='正在招聘')),
            ],
            options={
                'verbose_name': '招聘岗位',
                'verbose_name_plural': '招聘岗位',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ZhongKaoFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='回答')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '中考咨询',
                'verbose_name_plural': '中考咨询',
                'ordering': ['order'],
            },
        ),
    ]
