import time
import turtle

def draw_red_envelope():
    turtle.pensize(2)
    turtle.color('gold')
    turtle.penup()
    turtle.goto(0, -200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(200, 360)
    turtle.end_fill()

    turtle.pensize(4)
    turtle.color('brown')
    turtle.penup()
    turtle.pendown()
    turtle.circle(200, 360)

    turtle.pensize(2)
    turtle.color('white')
    turtle.penup()
    turtle.goto(-200, 85)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(0, 30)
    turtle.circle(-150, 60)
    turtle.circle(-15, 180)
    turtle.circle(120, 60)
    turtle.circle(-15, 180)
    turtle.penup()
    turtle.goto(50, 85)
    turtle.pendown()
    turtle.circle(-150, 60)
    turtle.circle(-15, 180)
    turtle.circle(120, 60)
    turtle.circle(-15, 180)
    turtle.end_fill()

    turtle.pensize(4)
    turtle.color('brown')
    turtle.penup()
    turtle.goto(-200, 85)
    turtle.pendown()
    turtle.circle(-150, 60)
    turtle.circle(-15, 180)
    turtle.circle(120, 60)
    turtle.circle(-15, 180)
    turtle.penup()
    turtle.goto(50, 85)
    turtle.pendown()
    turtle.circle(-150, 60)
    turtle.circle(-15, 180)
    turtle.circle(120, 60)
    turtle.circle(-15, 180)
    turtle.penup()
    turtle.goto(-155.9,-50)
    turtle.pendown()
    turtle.circle(0,-90)
    turtle.circle(180,120)

    turtle.pensize(6)
    turtle.pencolor('black')
    turtle.penup()
    turtle.goto(-100, 155)
    turtle.pendown()
    turtle.circle(0, 60)
    turtle.circle(30, 120)
    turtle.circle(0,180)
    turtle.penup()
    turtle.goto(100, 155)
    turtle.pendown()
    turtle.circle(-30, 120)

    turtle.pensize(2)
    turtle.pencolor('')
    turtle.penup()
    turtle.goto(-200,85)
    turtle.pendown()
    turtle.circle(0,90)
    turtle.circle(-150,15)
    turtle.pensize(2)
    turtle.pencolor('brown')
    turtle.begin_fill()
    turtle.circle(-15,360)
    turtle.end_fill()
    turtle.pencolor('')
    turtle.circle(-150, -15)
    turtle.penup()
    turtle.goto(50,85)
    turtle.pendown()
    turtle.circle(-150,15)
    turtle.begin_fill()
    turtle.pencolor('brown')
    turtle.circle(-15,360)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(300,-200)

    time.sleep(10)




draw_red_envelope()