import turtle

def draw_red_envelope():
    turtle.pensize(2)
    turtle.color('red')
    turtle.penup()
    turtle.goto(0, -200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.forward(150)
    turtle.circle(10, 90)
    turtle.forward(400)
    turtle.circle(10, 90)
    turtle.forward(300)
    turtle.circle(10, 90)
    turtle.forward(400)
    turtle.circle(10, 90)
    turtle.forward(150)
    turtle.end_fill()

    turtle.pensize(4)
    turtle.color('gold')
    turtle.penup()
    turtle.goto(0, -200)
    turtle.pendown()
    turtle.forward(150)
    turtle.circle(10, 90)
    turtle.forward(400)
    turtle.circle(10, 90)
    turtle.forward(300)
    turtle.circle(10, 90)
    turtle.forward(400)
    turtle.circle(10, 90)
    turtle.forward(150)

    turtle.pensize(4)
    turtle.color('gold')
    turtle.penup()
    turtle.goto(-160, 200)
    turtle.pendown()
    turtle.circle(0.01, 315)
    turtle.forward(215.5)
    turtle.circle(10, 90)
    turtle.forward(215.5)

    turtle.pensize(3)
    turtle.color('gold')
    turtle.penup()
    turtle.goto(0, 100)
    turtle.pendown()
    turtle.write("福", align="center" ,font=("楷体", 40, "normal"))
    turtle.pensize(3)
    turtle.color('gold')
    turtle.penup()
    turtle.goto(0, -30)
    turtle.pendown()
    turtle.write("巳巳如意", align="center", font=("楷体", 40, "normal"))
    turtle.penup()
    turtle.goto(0, -100)
    turtle.pendown()
    turtle.write("金榜题名", align="center", font=("楷体", 40, "normal"))
    turtle.done()

draw_red_envelope()