# Generated by Django 6.0.4 on 2026-05-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '章节', 'verbose_name_plural': '章节管理'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '作品', 'verbose_name_plural': '作品管理'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='work',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, verbose_name='正文内容'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='event_refs',
            field=models.JSONField(blank=True, null=True, verbose_name='事件关联'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='tech_refs',
            field=models.JSONField(blank=True, null=True, verbose_name='科技关联'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200, verbose_name='章节标题'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='chapters.work', verbose_name='所属作品'),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover_image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='封面图路径'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, verbose_name='作品简介'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=200, verbose_name='作品名称'),
        ),
    ]
