# Generated by Django 6.0.4 on 2026-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_alter_chapter_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'created_at'], 'verbose_name': '章节', 'verbose_name_plural': '章节管理'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序序号'),
        ),
    ]
