# Generated by Django 6.0.4 on 2026-05-08 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_alter_chapter_options_chapter_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='大纲节点标题')),
                ('content', models.TextField(blank=True, verbose_name='大纲内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chapters.outlinenode', verbose_name='父节点')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_nodes', to='chapters.work', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '大纲节点',
                'verbose_name_plural': '大纲节点管理',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='outline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='chapters.outlinenode', verbose_name='所属大纲节点'),
        ),
    ]
