# Generated by Django 6.0.4 on 2026-05-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_outlinenode_chapter_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='covers/', verbose_name='封面图'),
        ),
    ]
