# Generated by Django 4.2.30 on 2026-06-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_alter_work_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('word_count', models.IntegerField(default=0, verbose_name='码字数')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='创作时长(秒)')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
            },
        ),
    ]
