# Generated by Django 5.2.15 on 2026-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开显示')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PrincipalMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
            ],
            options={
                'verbose_name': '校长信箱',
                'verbose_name_plural': '校长信箱',
                'ordering': ['-sent_at'],
            },
        ),
    ]
