# Generated by Django 5.2.16 on 2026-07-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_id', models.CharField(max_length=100, unique=True, verbose_name='微信ID')),
                ('name', models.CharField(max_length=200, verbose_name='昵称')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注名')),
                ('contact_type', models.CharField(choices=[('personal', '个人'), ('group', '群组'), ('official', '公众号')], default='personal', max_length=20, verbose_name='类型')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=100, unique=True, verbose_name='消息ID')),
                ('msg_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('link', '链接'), ('system', '系统消息')], default='text', max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(blank=True, verbose_name='消息内容')),
                ('timestamp', models.DateTimeField(verbose_name='消息时间')),
                ('is_starred', models.BooleanField(default=False, verbose_name='是否星标')),
                ('is_from_self', models.BooleanField(default=True, verbose_name='是否自己发送')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.contact', verbose_name='联系人')),
                ('tags', models.ManyToManyField(blank=True, related_name='messages', to='core.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.IntegerField(default=0, verbose_name='未读数')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.contact', verbose_name='联系人')),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.message', verbose_name='最后一条消息')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='core_messag_timesta_647fca_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['contact', 'timestamp'], name='core_messag_contact_8d426b_idx'),
        ),
    ]
