# Generated by Django 5.2.17 on 2026-09-24 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_material_type', models.CharField(blank=True, default='', max_length=16)),
                ('active_hours', models.JSONField(default=dict, verbose_name='活跃时段分布 {"20":0.9, ...}')),
                ('subject_weights', models.JSONField(default=dict, verbose_name='主题权重 {"高等数学":0.8, ...}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习喜好',
                'verbose_name_plural': '学习喜好',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=200, verbose_name='推荐理由')),
                ('score', models.FloatField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='materials.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField()),
                ('total_duration_seconds', models.IntegerField(default=0, verbose_name='学习总时长（秒）')),
                ('materials_count', models.IntegerField(default=0, verbose_name='学习资料数')),
                ('kps_count', models.IntegerField(default=0, verbose_name='涉及知识点数')),
                ('avg_effective_rate', models.FloatField(default=0, verbose_name='平均有效率（完成/开始）')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-stat_date'],
                'unique_together': {('student', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='WeakKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_count', models.IntegerField(default=0)),
                ('mastery_level', models.FloatField(default=50, verbose_name='掌握度 0-100')),
                ('last_wrong_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_by', to='courses.knowledgepoint')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_kps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '薄弱知识点',
                'verbose_name_plural': '薄弱知识点',
                'ordering': ['-wrong_count'],
                'unique_together': {('student', 'kp')},
            },
        ),
    ]
