# Generated by Django 5.2.15 on 2026-06-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('slug', models.SlugField(unique=True, verbose_name='URL 别名')),
                ('content', models.TextField(help_text='支持 HTML', verbose_name='内容')),
                ('page_type', models.CharField(choices=[('about', '学校概况'), ('history', '历史沿革'), ('philosophy', '办学理念'), ('campus', '校园风光'), ('custom', '自定义页面')], default='custom', max_length=20, verbose_name='页面类型')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布')),
            ],
            options={
                'verbose_name': '固定单页',
                'verbose_name_plural': '固定单页',
            },
        ),
    ]
