# Generated by Django 5.2.15 on 2026-06-24 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL 别名')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('position', models.CharField(max_length=50, verbose_name='职务')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_photos', to='gallery.flowimage', verbose_name='照片')),
            ],
            options={
                'verbose_name': '领导',
                'verbose_name_plural': '领导',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='职称')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='organization.department', verbose_name='所属部门')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_photos', to='gallery.flowimage', verbose_name='照片')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'ordering': ['order', 'name'],
            },
        ),
    ]
