# Generated by Django 5.2.15 on 2026-07-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='链接名称')),
                ('url', models.URLField(max_length=500, verbose_name='链接地址')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
