# Generated by Django 5.2.17 on 2026-09-24 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('material_type', models.CharField(choices=[('document', '文档'), ('video', '视频'), ('link', '外链')], max_length=16, verbose_name='资料类型')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='文件')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='外链 URL')),
                ('duration', models.IntegerField(default=0, verbose_name='时长（秒，视频用）')),
                ('description', models.TextField(blank=True, default='', verbose_name='内容简介/富文本')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='课程')),
                ('kp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.knowledgepoint', verbose_name='知识点')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '学习资料',
                'verbose_name_plural': '学习资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.FloatField(default=0, verbose_name='进度（0-100）')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='本次学习时长（秒）')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False, verbose_name='是否学完')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='materials.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'ordering': ['-started_at'],
            },
        ),
    ]
