# Generated by Django 5.2.17 on 2026-10-01 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='成绩')),
                ('semester', models.CharField(blank=True, default='', max_length=16, verbose_name='学期（如 2025-2026-1）')),
                ('enrolled_at', models.DateField(auto_now_add=True, verbose_name='选课日期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_scores', to='accounts.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
