# Generated by Django 5.2.15 on 2026-07-08 23:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='班级名称')),
                ('grade', models.CharField(choices=[('7', '7年级'), ('8', '8年级'), ('9', '9年级'), ('10', '10年级'), ('11', '11年级'), ('12', '12年级')], max_length=2, verbose_name='年级')),
                ('year', models.PositiveSmallIntegerField(help_text='如 2023', verbose_name='入学年份')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前有效')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', '学生'), ('parent', '家长'), ('teacher', '教师'), ('whiteboard', '班级账户'), ('admin', '管理员')], default='student', max_length=20, verbose_name='角色')),
                ('real_name', models.CharField(blank=True, max_length=50, verbose_name='真实姓名')),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='学号/工号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('is_whiteboard', models.BooleanField(default=False, verbose_name='是否为班级账户')),
                ('whiteboard_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='长期令牌')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='gallery.flowimage', verbose_name='头像')),
                ('children', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='parents', to=settings.AUTH_USER_MODEL, verbose_name='关联孩子')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.classroom', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
