# Generated by Django 5.2.15 on 2026-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('parent', '家长'), ('teacher', '教师'), ('headteacher', '班主任'), ('dean', '教务主任'), ('principal', '校长'), ('whiteboard', '班级账户'), ('admin', '管理员')], default='student', max_length=20, verbose_name='角色'),
        ),
    ]
