# Generated by Django 5.2.15 on 2026-07-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('parent', '家长'), ('teacher', '教师'), ('head_teacher', '班主任'), ('academic_director', '教务主任'), ('principal', '校长'), ('counselor', '辅导员'), ('staff', '后勤/行政'), ('whiteboard', '班级账户'), ('admin', '管理员')], default='student', max_length=20, verbose_name='角色'),
        ),
    ]
