# Generated by Django 5.2.15 on 2026-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学校全称')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='简称')),
                ('logo_usage', models.CharField(default='logo', help_text='对应 gallery_staticimage 表中的 usage 字段，用于调用本地图片库中的 Logo', max_length=50, verbose_name='Logo 用途标识')),
                ('brief_intro', models.TextField(blank=True, max_length=500, verbose_name='一句话简介')),
                ('about', models.TextField(blank=True, verbose_name='学校概况')),
                ('history', models.TextField(blank=True, verbose_name='历史沿革')),
                ('philosophy', models.TextField(blank=True, verbose_name='办学理念')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('website', models.URLField(blank=True, verbose_name='官网地址')),
            ],
            options={
                'verbose_name': '学校信息',
                'verbose_name_plural': '学校信息',
            },
        ),
    ]
