# Generated by Django 5.2.15 on 2026-06-24 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('graduate_year', models.PositiveSmallIntegerField(verbose_name='毕业年份')),
                ('achievement', models.CharField(max_length=200, verbose_name='成就/去向')),
                ('story', models.TextField(blank=True, verbose_name='成长故事')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduate_photos', to='gallery.flowimage', verbose_name='照片')),
            ],
            options={
                'verbose_name': '优秀毕业生',
                'verbose_name_plural': '优秀毕业生',
                'ordering': ['order', '-graduate_year'],
            },
        ),
    ]
