# Generated by Django 5.2.16 on 2026-07-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('platform', models.CharField(choices=[('wechat_work', '企业微信'), ('personal', '个人微信'), ('official_account', '微信公众号')], max_length=20, verbose_name='平台类型')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '异常')], default='offline', max_length=20, verbose_name='状态')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '微信账户',
                'verbose_name_plural': '微信账户',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50, verbose_name='同步类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('running', '进行中')], max_length=20, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='日志信息')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='wechat_bridge.wechataccount', verbose_name='账户')),
            ],
            options={
                'verbose_name': '同步日志',
                'verbose_name_plural': '同步日志',
                'ordering': ['-started_at'],
            },
        ),
    ]
