# Generated by Django 5.2.15 on 2026-06-24 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='相册名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL 别名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流动相册',
                'verbose_name_plural': '流动相册',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image_path', models.CharField(help_text='相对于 static/gallery/ 的路径，例如 "logo.png" 或 "banner/hero.jpg"', max_length=255, verbose_name='图片路径')),
                ('usage', models.CharField(help_text='唯一标识，如 "logo"、"home_banner"、"wechat_qr"', max_length=50, unique=True, verbose_name='用途')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '本地图片',
                'verbose_name_plural': '本地图片',
            },
        ),
        migrations.CreateModel(
            name='FlowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='上传后自动按年月分目录存放', upload_to='gallery/albums/%Y/%m/', verbose_name='图片文件')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='标题/说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.flowalbum', verbose_name='所属相册')),
            ],
            options={
                'verbose_name': '流动图片',
                'verbose_name_plural': '流动图片',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='flowalbum',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_of_album', to='gallery.flowimage', verbose_name='封面图片'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('video_url', models.URLField(blank=True, help_text='如腾讯视频、B站嵌入地址，留空则使用上传文件', verbose_name='视频链接')),
                ('video_file', models.FileField(blank=True, help_text='直接上传视频文件（优先于链接）', upload_to='gallery/videos/%Y/%m/', verbose_name='视频文件')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/videos/thumbnails/', verbose_name='封面缩略图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='gallery.flowalbum', verbose_name='所属相册（可选）')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-created_at'],
            },
        ),
    ]
